### ISSUE TITLE
References to the 'Data' tab should be 'Variables'

### ISSUE THREAD

**Issue by LucyParry** [raspberrypilearning/poetry-generator#18]
In steps 4 and 5, should the references to the 'Data' tab actually be the 'Variables' tab? (I believe it was 'Data' in Scratch 2).

Happy to submit a PR if so (should this be the draft branch or the master branch?)

I also spotted a very minor typo in part 10 ('you own poetry' should be 'your own poetry')

**Comment by ninaszymor** [comment]
@rik-cross do you think someone could take a look at this? It's a quick change which I think is quite important. I have had this pointed out by a few translators.

**Comment by rik-cross** [comment]
Thanks @LucyParry. I've corrected the errors you mention -- thanks for spotting them and letting us know!

cc. @ninaszymor
